#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionASP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProyectoMuestraASP1")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProyectoMuestraASP1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<contacto_mensajes> contacto_mensajes
		{
			get
			{
				return this.GetTable<contacto_mensajes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.contacto_mensajes")]
	public partial class contacto_mensajes
	{
		
		private int _cmje_id;
		
		private string _cmje_nombre;
		
		private string _cmje_mail;
		
		private string _cmje_mensaje;
		
		private System.DateTime _cmje_fecha;
		
		public contacto_mensajes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmje_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int cmje_id
		{
			get
			{
				return this._cmje_id;
			}
			set
			{
				if ((this._cmje_id != value))
				{
					this._cmje_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmje_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cmje_nombre
		{
			get
			{
				return this._cmje_nombre;
			}
			set
			{
				if ((this._cmje_nombre != value))
				{
					this._cmje_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmje_mail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cmje_mail
		{
			get
			{
				return this._cmje_mail;
			}
			set
			{
				if ((this._cmje_mail != value))
				{
					this._cmje_mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmje_mensaje", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string cmje_mensaje
		{
			get
			{
				return this._cmje_mensaje;
			}
			set
			{
				if ((this._cmje_mensaje != value))
				{
					this._cmje_mensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmje_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime cmje_fecha
		{
			get
			{
				return this._cmje_fecha;
			}
			set
			{
				if ((this._cmje_fecha != value))
				{
					this._cmje_fecha = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
