<?xml version="1.0" encoding="utf-8"?><Database Name="ProyectoMuestraASP1" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ProyectoMuestraASP1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProyectoMuestraASP1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.contacto_mensajes" Member="contacto_mensajes">
    <Type Name="contacto_mensajes">
      <Column Name="cmje_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cmje_nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cmje_mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cmje_mensaje" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="cmje_fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>